### ISSUE TITLE
hdr.bounce check together with contradictory trace message

### ISSUE THREAD

**Issue by unboxedtype** [tonlabs/ton-labs-executor#27]
Hi!

https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L1058

There is a check for hdr.bounce flag set, but the message states the opposite: 

https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L1059

Is it intentionally done this way or is it a misspelling or is it an error? 

Thanks!

**Comment by sv-91** [comment]
There is an error in the message. This will be fixed
