### ISSUE TITLE
SENDMSG_IGNORE_ERROR action processing logic question

### ISSUE THREAD

**Issue by unboxedtype** [tonlabs/ton-labs-executor#28]
Hi!

This skip boolean is used only once, during some error propagation code:

https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L797

Are you sure this flag is fully implemented? In the old TON-1 node, there were at least 10 places they used the skip check. In your code, I see none.

**Comment by sv-91** [comment]
Instead SENDMSG_IGNORE_ERROR flag, here is used skip variable. The total number of uses of the flag is different due to the different ways to message processing

**Comment by unboxedtype** [comment]
Sorry, could you please elaborate. I see the following:

```
    let skip = if (mode & SENDMSG_IGNORE_ERROR) != 0 {
        None
    } else {
        Some(())
    };
```
If SENDMSG_IGNORE_ERROR flag is set, then **skip** equals to **None**. 
Then goes the processing logic:
```
    if acc_balance.grams.0 < result_value.grams.0 {
        log::warn!(
            target: "executor", 
            "account balance {} is too small, cannot send {}", acc_balance.grams, result_value.grams
        ); 
        return Err(skip.map(|_| RESULT_CODE_NOT_ENOUGH_GRAMS).unwrap_or(0))
    }
```
The above code returns Err(0) in case the **skip** is set to **None**, right?

Then, the outer dispatcher in action_phase is this:
```
 match result {
  Ok(_) => {
    phase.msgs_created += 1;
    out_msgs0.push((mode, out_msg));
    0
  }
  Err(code) => code
 }
```
So, the message will not be put into the out_msg queue? What am I missing here?

**Comment by unboxedtype** [comment]
I just realized this is exactly the expected behavior for this flag, no comments needed.
