### ISSUE TITLE
Action phase: processing messages with SENDMSG_ALL_BALANCE flag

### ISSUE THREAD

**Issue by unboxedtype** [tonlabs/ton-labs-executor#29]
Hi!

The processing logic of messages with SENDMSG_ALL_BALANCE seems incorrect to me. Could you please prove me wrong. Take in mind that Rust is not my native language, so I may miss something important.

During the processing of actions, starting at : 
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L488

you put all messages with the flag into out_msgs0 collection, skipping their processing with 'continue' statment.

```
if (mode & SENDMSG_ALL_BALANCE) != 0 {
        out_msgs0.push((mode, out_msg));
        continue
}
```
After this initial iteration over the action list, you start to process out_msgs0 collection. But, this time, you also
skip messages with this flag set, using the same continue statement. You put them into out_msgs collection without processing.
```
 for (i, (mode, mut out_msg)) in out_msgs0.into_iter().enumerate() {
            if (mode & SENDMSG_ALL_BALANCE) == 0 {
                out_msgs.push(out_msg);
                continue
  }
```
This is strange, because the outmsg_action_handler contains the logic for processing messages with this flag set.
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L837

Am I missing something?

**Comment by sv-91** [comment]
Messages with flag SENDMSG_ALL_BALANCE are processed last. But order of messages does not change. Therefore message processing is divided into 2 phases

**Comment by unboxedtype** [comment]
From what I see, you first move such messages from actions vector into the out_msgs0 vector w/o any processing
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L544

Next, you move them from out_msgs0 into out_msgs, again, w/o any processing
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L590

How it comes that they get finally processed?
