### ISSUE TITLE
Frozen accounts recovery logic is missing?

### ISSUE THREAD

**Issue by unboxedtype** [tonlabs/ton-labs-executor#31]
Hi!

My question belongs to the logic of the function:
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/ordinary_transaction.rs#L62

Consider the following case:
1) We have an active account with some balance that is not enough to cover fwd_fee + storage_fee.
2) The incoming message is internal and has bounce flag unset and has some value attached to it.

After processing the storage phase, the account will become frozen due to condition (1):
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/transaction_executor.rs#L235

Next, we go to the credit phase. It increases the balance of the account by the message value, but the account is still in 
frozen state, you do not switch it back to Active, despite the fact that its balance is now non-negative and could cover the due expenses.

What is worse, you now go to compute phase and spend gas despite the fact that the account is frozen and has no state
that could be changed further (only state_init hash).

You the finalize the account state in:
https://github.com/tonlabs/ton-labs-executor/blob/be2f1ec60e09857d8b8f489c1e79f000bba32269/src/ordinary_transaction.rs#L237

Am I missing something? Is it by design?

**Comment by sv-91** [comment]
Account will be unfrozen in line 
`if let Some(reason) = compute_new_state(&mut result_acc, &acc_balance, msg, init_code_hash) {`
in compute_phase

**Comment by unboxedtype** [comment]
Yes, thanks.
